config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/backstage', as: 'rails_admin'
  get 'homes/index'

  resources :coupons, only: [:index, :show]
  resources :services, only: [:index, :show]
  resources :homes, only: [:index, :show]

  root 'homes#index'

end

app/models/coupon.rb
class Coupon < ActiveRecord::Base
  belongs_to :service
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/service.rb
class Service < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

helper_method :all_services
def all_services
  @services ||=  Service.all
end  
end

app/controllers/coupons_controller.rb
class CouponsController < ApplicationController
  def index
    @coupons = Coupon.all
  end

  def show
    render layout: false
    @coupon = Coupon.find(params[:id])
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def index
    @services = Service.all
  end

  def show
    @service = Service.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coupons_helper.rb
module CouponsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/coupons/index.html.erb
<h1 align="left">Coupons</h1>

<p align="left">These coupons may be used at M &amp; M Service in Taylorsville, Utah. ADDITIONAL COUPONS can be found by clicking on the services listed at the right.</p>

<p class="style6" align="center">CLICK ON COUPON FOR EASY PRINTING</p>

<% @coupons.each do |coupon| %>
    <article>
        <h1 class="coupon_title"><%= coupon.title %></h1>
        <%= link_to image_tag("web10_png.png", class: "coupon"), coupon_path(coupon) %>
    </article>

<% end %>

app/views/coupons/show.html.erb
<html>
  <head>

  </head>
  <body>
    <%= image_tag("web10_png.png") %>
  </body>
</html>

app/views/homes/index.html.erb
<header>
  <div class="wrapper">
    <div class="mobile-menu-icon">mm icon</div>
  </div>
</header>
<div class="wrapper">
  <div class="main-content">
    <div class="intro">intro</div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html >
  <head>
    <meta charset="UTF-8">
    <title>M&amp;M Service</title>
    <style>
    </style>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

  </head>
  <body>
    <div class="box">
      <header>
        <div class="logo_and_title">
          <a href="/"><div class="logo"></div></a>
          <h1><a href="/">M&amp;M Service</a></h1>
        </div>
        <nav><a href="/" class="nav_link">Home</a> <a href="/services" class="nav_link">Services</a> <a href="/coupons" class="nav_link">Coupons</a> <a href="/pages/contact_us" class="nav_link">Location</a> <a href="pages/contact_us" class="nav_link">Contact</a></nav>
      </header>

      <!--Left Column--->

      <section class="mainkazoo">
          <%= yield %>
      </section>

      <!--Right Column--->

      <section class="sidebarkazoo">
      <article class="reverse">
      <p>&nbsp;</p>

          <h2>M&amp;M<br> Maintenance Services</h2>
          <div class="sidebarlist" align="left">

          <%= render :partial => "shared/service_listing", :collection => all_services %>
          <p>&nbsp;&nbsp;</p>
          </div>
          <p class="sidebar" align="left">These services are available at M&amp;M Service in Utah. Click on the links above to get <a href="/services">more information on each service.</a></p>
      </article>
      </section>
      <footer>
        <hr />
        <p>These services are available at these M&amp;M Services in Utah. Visit our location page for specific addresses, phone numbers and links to maps and list of services.</p>
        <p class="copyright">Copyright Dice Media Group 2016</p>
      </footer>

      <div class="jump">
        <a href="#top"><div class="up"></div></a>
      </div>
    </div>
  </body>
</html>

app/views/layouts/coupons.html.erb
<!DOCTYPE html> 
<html xmlns=http://www.w3.org/1999/xhtml> 
    <head> 
        <title>Barbarian meets coding - Flexbox - Example App - BLOG!</title> 
        <meta charset=utf-8> 
        <meta name=description content="Barbarian meets coding - Flexbox - Example App - BLOG!"> 
        <meta name=viewport content="width=device-width"> 
        <link rel="shortcut icon" href="http://www.barbarianmeetscoding.com/barbaric-basics-web-development/css-layout-dist//6df2b309.favicon.ico"> 
        <link rel=stylesheet href="http://www.barbarianmeetscoding.com/barbaric-basics-web-development/css-layout-dist/styles/66dbb628.main.css"> 
        <link rel=stylesheet href="http://www.barbarianmeetscoding.com/barbaric-basics-web-development/css-layout-dist/styles/blog.css"> 
        <script src="http://www.barbarianmeetscoding.com/barbaric-basics-web-development/css-layout-dist/bower_components/modernizr/modernizr.js" ></script>  
    </head>
        <body> 
            <header class=flex-container> 
                <section class=brand> 
                    <h1>M &amp; M Service</h1> 
                </section> 
                <nav class=flex-container> 
                    <ul class=flex-container> 
                        <li><%= link_to "Home", root_path %> </li> 
                        <li><%= link_to "Coupons", coupons_path %></li> 
                        <li><a href=#>Contact</a></li> 
                    </ul> 
                </nav> 
            </header> 
            <section class="main-content flex-container"> <section> 
                <%= yield %>

            </section> 
            <aside> 
                <section class=my-bio> 
                    <figure class=flex-container> <img src="http://www.barbarianmeetscoding.com/barbaric-basics-web-development/css-layout-dist/images/ef3ed238.cat-suit.jpg" width="200"> 
                        <figcaption> Hi! I am William Catspeare the IIIrd, I love playing with yarn and hunting mice. Welcome to my blog! Hope you Like it! Meeeeouw. 
                        </figcaption> 
                    </figure> 
                </section> 
            </aside> 
        </section> 
        <footer class=flex-container> <p>Copyright 2015 Catbarian meets coding.</p> </footer>  

app/views/layouts/coupons_old.html.erb
<!DOCTYPE html> 
<html xmlns=http://www.w3.org/1999/xhtml> 
    <head> 
        <title>M &amp; M Service</title> 
        <meta charset=utf-8> 
        <meta name=description content="Barbarian meets coding - Flexbox - Example App - BLOG!"> 
        <meta name=viewport content="width=device-width"> 
        <%# stylesheet_link_tag "blog", :cache => true %>
        <link rel="shortcut icon" href="http://www.barbarianmeetscoding.com/barbaric-basics-web-development/css-layout-dist//6df2b309.favicon.ico"> 
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    </head>
        <body> 
            <header class=flex-container> 
                <section class=brand> 
                    
                    <img src="/mmservicestationbannerandlogo1.gif" width="850" height="155" alt="Mmservicestationbannerandlogo1">
                </section> 
                <nav class=flex-container> 
                    <ul class=flex-container> 
                        <li><%= link_to "Home", root_path %> </li> 
                        <li><%= link_to "Coupons", coupons_path %></li> 
                        <li><a href=#>Contact</a></li> 
                    </ul> 
                </nav> 
            </header> 
            <section class="main-content flex-container"> <section> 
                <%= yield %>

            </section> 
            <aside> 
                <h1><a href="/">M&amp;M Service</a></h1>
                <section class="service-listings">
                    <p>&nbsp;</p>
                    <%= render :partial => "shared/service_listing", :collection => all_services %>
                    
                </section>
            </aside> 
        </section> 
        <footer class=flex-container> <p>Copyright Dice Media Group.</p> </footer>  

app/views/layouts/homes.html.erb
<!DOCTYPE html>
<head>
    <meta charset="UTF-8">
    <title>M&amp;M Service Station</title>
    <%= stylesheet_link_tag "application" %>
    <meta name="viewport" content="initial-scale=1.0">
</head>

<header>
  <div class="wrapper">
    <%= link_to(root_path) do %><div class="logo"></div><% end %>
    
    <div class="site-title">
        <h1><%= link_to "M&M Service", root_path %></h1>
    </div>
    <div class="navigation">
        <%= link_to "Home", homes_path, class: "icon" %>
        <%= link_to "Coupons", coupons_path, class: "icon" %>
        <%= link_to "Services", services_path, class: "icon" %>
        <%= link_to "Fleet", services_path, class: "icon" %>
        <%= link_to "Location", homes_path, class: "icon" %>
        
    </div>
    <div class="mobile-menu-icon"></div>
  </div>
</header>
<div class="wrapper">
  <div class="main-content">
    <div class="intro featured-promos">
        <div class="promo">promo</div>
        <div class="promo">promo</div>
        <div class="promo">promo</div>
    </div>
    <aside class="sidebar">
        <h2><a href="/">M&amp;M Service</a></h2>
        
        <div class="sidebarlist">
            <ul>
                <p>&nbsp;</p>
                <%= render :partial => "shared/service_listing", :collection => all_services %>
            </ul>
        </div>
    </aside>
  </div>
  <div class="featured-tiles">
    <div class="tile">tile1</div>
    <div class="tile">tile2</div>
    <div class="tile">tile3</div>
    <div class="tile">tile4</div>
  </div>
</div>
    <!-- <meta charset="UTF-8">
    <title>M&amp;M Service Station</title>
    <%= stylesheet_link_tag "application" %>
</head>
<header>
  <div class="wrapper">
    <a href="/"><div class="logo"></div></a>

    <nav class="navigation">
        <div class="icon"><%= link_to "Home", root_path %></div>
        <div class="icon"><%= link_to "Service", services_path %></div>
        <div class="icon"><%= link_to "Coupons", coupons_path %></div>
        <div class="icon"><%= link_to "Our Location", "/contact_us" %></div>
    </nav>
    <div class="mobile-menu-icon">mm icon</div>
  </div>
</header>

<div class="wrapper">
  <div class="main-content">
    <%= yield %>
    <div class="sidebar">Sidebar Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</div>
  </div>
      <div class="featured-tiles">
        <div class="tile">tile1</div>
        <div class="tile">tile2</div>
        <div class="tile">tile3</div>
        <div class="tile">tile4</div>
      </div>
</div> -->

app/views/pages/welcome.html.erb
<script language=javascript>
<!--
var redirectagent = navigator.userAgent.toLowerCase();
var redirect_devices = ['vnd.wap.xhtml+xml', 'sony', 'symbian', 'nokia', 'samsung', 'mobile', 'windows ce', 'epoc', 'opera mini', 'nitro', 'j2me', 'midp-', 'cldc-', 'netfront', 'mot', 'up.browser', 'up.link', 'audiovox', 'blackberry', 'ericsson', 'panasonic', 'philips', 'sanyo', 'sharp', 'sie-', 'portalmmm', 'blazer', 'avantgo', 'danger', 'palm', 'series60', 'palmsource', 'pocketpc', 'smartphone', 'rover', 'ipaq', 'au-mic', 'alcatel', 'ericy', 'vodafone', 'wap1', 'wap2', 'teleca', 'playstation', 'lge', 'lg-', 'iphone', 'android', 'htc', 'dream', 'webos', 'bolt', 'nintendo'];
for (var i in redirect_devices) {
if (redirectagent.indexOf(redirect_devices[i]) != -1) {
location.replace("http://jiffylubeutah.com/mobile/");
}
}
-->
</script>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta name="google-site-verification" content="arHr00XC_A7hYx-d5iIo-gM1WpcElw37N7IIP9vckDI" />
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<title>Utah Jiffy Lube | Oil Change Coupons, Automotive Maintenance | Located Throughout the Utah Area</title>
<meta name="description" content="Utah oil changes and other automotive by Jiffy Lube.  Visit your nearest Utah Jiffy Lube for a quality oil change and other automotive services." />
<meta name="keywords" content="Utah, oil change, automotive" />
<link href="main2.css" rel="stylesheet" type="text/css" />
<style type="text/css">
<!--
#apDiv1 {
	position:absolute;
	left:1169px;
	top:752px;
	width:128px;
	height:123px;
	z-index:2;
}
#apDiv2 {
	position: absolute;
	z-index: 2;
	left: 509px;
	top: 739px;
}
-->
</style>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-38054726-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</head>
<body background="images/global_bg.gif">
<div id="Content">
<div id="Layer1">
<div class="style1" id="Layer5">Utah Jiffy Lube<span class="style5"><sup>&reg;</sup></span></div>
<div class="style2" id="Layer6">Get a quality oil change at any of our Utah locations.</div>
<div class="menu" id="Layer3"><a href="index.htm">Home</a> &nbsp; <a href="locations.htm"></a><a href="coupons.htm">Coupons</a> &nbsp; <a href="services.htm">Services</a> &nbsp; <a href="fleet.htm">Fleet </a> &nbsp; <a href="http://jiffylubevipdiscount.com/" target="_blank">VIP Cards</a> &nbsp; <a href="http://jiffylube.com/giftcard/giftcard.aspx">Gift Cards</a> &nbsp; <a href="employment.htm">Jobs</a> &nbsp; <a href="contact.htm">Contact</a></div>
<div class="locator" id="Layer4"><a href="locations.htm">Jiffy Lube Locations</a></div>
<div id="Layer7">
<div class="locator">Community Service</div>
<p align="center">&nbsp;</p>
<p align="center"><a href="http://www.yourturn2apply.com/utah.htm"><img src="images/teendriver.gif" border="0" height="130" width="200" /></a></p>
<hr align="center" width="170" />
<div align="left">
<p>The Jiffy Lube &quot;What Drives You?&quot; High School Scholarship program is a unique opportunity to pursue your interests, goals and ideas.</p>
</div>
</div>
<div id="Layer8">
<div class="locator"><a href="http://jiffylubevipdiscount.com/" target="_blank">Business VIP Cards</a></div>
<p align="center"><br /> <img src="images/vip_cards3.jpg" alt="Jiffy Lube VIP Card" height="130" width="200" /></p>
<h2>Treat your employees<br /> like VIPs!</h2>
<p class="sidebar">Reward them with generous discounts at Jiffy Lube. <a href="http://jiffylubevipdiscount.com/" target="_blank">Order your FREE VIP Discount Cards</a> now.</p>
<p class="sidebar"></p>
</div>
<div id="Layer9">
<div class="locator"><a href="services.htm">Jiffy Lube Services</a></div>
<div class="sidebarlist">
<p>&nbsp;</p>
<p><a href="signature_service.htm">Jiffy Lube Signature Service&reg; Oil Change</a></p>
<p><a href="ac_service.htm">A/C Evacuation and Recharge Service</a></p>
<p><a href="automatic_transmission_service.htm">Automatic Transmission Services</a></p>
<p><a href="battery_service.htm">Battery Maintenance Services</a></p>
<p><a href="brake-replacement-service.htm">Brake Replacement &amp; Repair Service</a></p>
<p><a href="differential_service.htm">Differential Service</a></p>
<p><a href="air_filter_service.htm">Engine Air Filtration Service</a></p>
<p><a href="fuel_filter_service.htm">Fuel Filter Replacement</a></p>
<p><a href="fuel_system_service.htm">Fuel System Cleaning Service</a></p>
<p><a href="manual_transmission_service.htm">Manual Transmission Service</a></p>
<p><a href="radiator_coolant_service.htm">Radiator Antifreeze/Coolant Service</a></p>
<p><a href="safety_inspection.htm">Safety Inspection &amp; Emissions Test</a></p>
<p><a href="serpentine_belt_replacement.htm">Serpentine Belt Replacement</a></p>
<p><a href="tire_rotation_service.htm">Tire Rotation Service</a></p>
<p><a href="transfer_case_service.htm">Transfer Case Service</a></p>
<p><a href="windshield_repair_service.htm">Windshield Repair Service</a></p>
<p><a href="windshield_wiper_replacement.htm">Windshield Wiper Replacement</a></p>
</div>
</div>
<div id="Layer2">
<table background="images/bg_bar.gif" border="0" cellpadding="0" cellspacing="0" width="755">
<tbody>
<tr>
<td>
<table align="center" border="0" cellpadding="0" cellspacing="0" width="731">
<tbody>
<tr>
<td width="731"><img src="images/header2.gif" usemap="#Map" href="index.htm" border="0" height="173" width="731" /></td>
</tr>
<tr>
<td>
<table border="0" cellpadding="0" cellspacing="0" width="731">
<tbody>
<tr>
<td colspan="2" valign="top">
<table border="0" cellpadding="0" cellspacing="0" width="731">
<tbody>
<tr>
<td width="509">
<div align="center"><a href="http://jiffylubeutah.com/mydashboard.htm"><img src="images/UT-Web-dashboard-banner.jpg" alt="More Than Oil Change" height="202" width="508" /></a></div>
</td>
<td valign="top" width="222">
<p><a href="coupons.htm"><img src="images/10off.gif" alt="$7 Off Link" border="0" height="110" width="223" /></a></p>
<table align="center" border="0" cellpadding="0" cellspacing="0" width="190">
<tbody>
<tr>
<td>
<div align="left">Add life to your car with added savings! <a href="coupons.htm">Get $10 off a Jiffy Lube Signature Service&reg; Oil Change.</a></div>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td colspan="2" valign="top">
<table border="0" cellpadding="5" cellspacing="0" width="731">
<tbody>
<tr>
<td height="471" valign="top"><img src="images/home_promo3.jpg" height="450" width="243" /></td>
<td valign="top"><img src="images/home_promo3.jpg" height="450" width="243" /></td>
<td valign="top">
<div id="apDiv2"><img src="images/socialMEDIALINK.gif" usemap="#Map2" border="0" height="98" width="223" /></div>
<img src="images/home_promo3.jpg" height="450" width="243" /></td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td><img src="images/spacer.gif" height="10" width="513" /></td>
<td><img src="images/spacer.gif" height="10" width="217" /></td>
</tr>
<tr>
<td colspan="2">
<p class="sidebar"><a href="privacy_policy.htm">Privacy Policy</a></p>
<p class="footer"><a href="http://www.jiffylube.com/">Jiffy Lube&reg;, the pioneer of the oil change industry, delivers experience in vehicle maintenance.</a></p>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
</tbody>
</table>
</td>
</tr>
<tr>
<td><img src="images/footer2.gif" height="45" width="755" /></td>
</tr>
</tbody>
</table>
<table align="center" border="0" cellpadding="0" cellspacing="12" width="500">
<tbody>
<tr>
<td colspan="3" valign="top" width="33%">
<div align="left">
<p>These services are available at these <a href="locations.htm">Jiffy Lube locations</a> in Utah. Visit our <a href="locations.htm">locations page</a> for specific addresses, phone numbers and links to maps and list of services.</p>
</div>
</td>
</tr>
<tr>
<td valign="top">
<div align="left"><strong>UTAH</strong><br /> American Fork, UT <br /> Bountiful, UT <br /> Brigham City, UT <br /> Cedar City, UT <br /> Draper, UT <br /> Herriman, UT <br /> Highland, UT <br /> Holladay, UT <br /> Kaysville, UT <br /> Kearns, UT <br /> Layton, UT</div>
</td>
<td valign="top">
<div align="left"><strong><br /> </strong>Lehi, UT <br /> Lindon, UT <br /> Logan, UT <br /> Magna, UT<br /> Murray, UT <br /> North Salt Lake, UT<br /> Ogden, UT<br /> Orem, UT<br /> Provo, UT<br /> Riverton, UT<br /> Roy, UT</div>
</td>
<td valign="top">
<div align="left"><br /> Salt Lake City, UT<br /> Sandy, UT<br /> Saratoga Springs, UT<br /> Springville, UT<br /> St. George, UT<br /> Sugarhouse, UT<br /> Tooele, UT<br /> Tremonton, UT<br /> Washington, UT<br /> West Jordan, UT<br /> West Valley, UT</div>
</td>
</tr>
</tbody>
</table>
<p class="sidebarlist style6" align="center">&nbsp;</p>
</div>
</div>
</div>
<p><map name="Map" id="Map">
<area shape="rect" coords="8,4,240,74" href="index.htm" />

<area shape="rect" coords="633,5,730,45" href="http://www.jiffylubeutah.com/competitive_call/report" />
 </map></p>
<p></p>
<p><map name="Map3" id="Map3">
<area shape="rect" coords="8,161,215,197" href="blast08.htm" />
 </map> <map name="Map4" id="Map4">
<area shape="rect" coords="11,8,199,180" href="blast09.htm" />
 </map> <map name="Map2">
<area shape="rect" coords="41,47,77,89" href="http://www.jiffylubeutah.blogspot.com" />

<area shape="rect" coords="91,49,131,87" href="http://www.facebook.com/pages/Jiffy-Lube-Utah/197713506911636" />

<area shape="rect" coords="143,49,182,89" href="http://twitter.com/#!/jiffylubeutah" />
 </map></p>
<!-- Google Code for Remarketing tag -->
<p></p>
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">// <![CDATA[
var google_conversion_id = 988515769;
var google_conversion_label = "2WsXCK-_pgQQuZuu1wM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
// ]]></script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">// <![CDATA[

// ]]></script>
<noscript><div style="display:inline;"> <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/988515769/?value=0&amp;label=2WsXCK-_pgQQuZuu1wM&amp;guid=ON&amp;script=0"/> </div></noscript><!-- Google Code for Remarketing tag -->
<p></p>
<!-- Remarketing tags may not be associated with personally identifiable information or placed on pages related to sensitive categories. For instructions on adding this tag and more information on the above requirements, read the setup guide: google.com/ads/remarketingsetup -->
<script type="text/javascript">// <![CDATA[
var google_conversion_id = 988515769;
var google_conversion_label = "2WsXCK-_pgQQuZuu1wM";
var google_custom_params = window.google_tag_params;
var google_remarketing_only = true;
// ]]></script>
<script type="text/javascript" src="//www.googleadservices.com/pagead/conversion.js">// <![CDATA[

// ]]></script>
<noscript><div style="display:inline;"> <img height="1" width="1" style="border-style:none;" alt="" src="//googleads.g.doubleclick.net/pagead/viewthroughconversion/988515769/?value=0&amp;label=2WsXCK-_pgQQuZuu1wM&amp;guid=ON&amp;script=0"/> </div></noscript>
</body>
</html>

app/views/services/index.html.erb
<article>



  <p>These services are available at M&amp;M Services. Click on each service for more information or visit our coupon page to get a <%= link_to "M & M Coupon", coupons_path() %> for that service.</p>

  <p><strong>M&amp;M SERVICE MAINTENANCE SERVICES</strong></p>

  <ul>
    <% @services.each do |service| %>
    <li><%= link_to service.title, service_path(service) %></li>
    <% end %>

  </ul>

  <p>&nbsp;</p>

</article>

app/views/services/show.html.erb
<article>
  <h1><%= @service.title %></h1>
  <p>&nbsp;</p>
  <%= @service.description %>
  
</article>

app/views/shared/_listing_of_service_offered.html.erb
        <p>&nbsp;</p>
        <%= render :partial => "shared/service_listing", :collection => all_services %>

app/views/shared/_service_listing.html.erb
        <li><%= link_to service_listing.title, service_path(service_listing) %></li>